### ISSUE TITLE
Add Homepage with Navbar

### ISSUE THREAD

**Issue by VishalZ123** [AISocietyIITJ/raid_website_frontend#1]
Search and implement a good navbar design on the home page. The navbar should contain a logo, Home and Teams options.
You can use pre-existing components online e.g.- Chakra UI etc.
The theme of the website would be dark, so search accordingly.

**Comment by adityarathor007** [comment]
Hello, @VishalZ123  I would like to contribute in this issue. As suggested I will be using Chakra Ui for creating the navbar design.Instead of titles I will be using icons in sync with the dark theme.

**Comment by VishalZ123** [comment]
@adityarathor007 
If you have searched for any navbar templates, kindly share it here.
Also for now, lets skip the logo titles and use text tiles for home and team links on the navbar.

**Comment by adityarathor007** [comment]
https://www.figma.com/community/file/1168793531845613848/Trendy-Navigation-bar-design 

what I tried
(https://github.com/AISocietyIITJ/raid_website_frontend/assets/120591213/caaff8c4-e286-4484-8cb8-25a9cb7f596d)

**Comment by VishalZ123** [comment]
<img width="500" alt="image" src="https://github.com/AISocietyIITJ/raid_website_frontend/assets/76409986/7843a396-b170-4c11-8241-cf6da75cfe6f">

We need something like this, the Home and Teams option would appear below the image in the bottom left.
Let's not keep the icons.

**Comment by adityarathor007** [comment]
(https://github.com/AISocietyIITJ/raid_website_frontend/assets/120591213/5dbe587f-63a9-4f59-a990-5e2a6a2d8347)

I was not able to get the bg image so I did this

**Comment by VishalZ123** [comment]
Okay, I am assigning it to you. @adityarathor007

**Comment by VishalZ123** [comment]
@adityarathor007 
PFA the image - https://drive.google.com/file/d/1Cvbuppw75FCX-qpsXd8obrbNqcIMRNsx/view?usp=sharing

**Comment by VishalZ123** [comment]
Closed via #5
